spring:
  application:
    name: aws-practice
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # ????? ??? ??? ??? ?????, ???? :???? ?? ? ??
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database: mysql
    # ?? ????? ?? 'create'? 'update'? ?? ?? 'validate'? 'none'? ???.
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true # ??? ??? SQL? ??? ??
        default_batch_fetch_size: 100 # N+1 ?? ??? ?? ?? (????)